spring:
  application:
    name: todo_alpha

  datasource:
    url: jdbc:postgresql://localhost:5432/archive
    username: archive_user
    password: archive_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000
        loggerLevel: FULL

logging:
  level:
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    todo_alpha.todo_alpha: DEBUG

seoul:
  base-url: "http://openapi.seoul.go.kr:8088"
  api-key: "70766e7558646c77313236557362656a"
  type: "json"
